{"name": "src.utils.snk_requester", "timestamp": "2025-04-25T17:19:25Z", "severity": "ERROR", "filename": "snk_requester.py", "lineno": 97, "process": 863248, "message": "Erro no servi\u00e7o DatasetSP.loadRecords: status=3, message=N\u00e3o autorizado."}
